### PR TITLE
Default to the local unix domain socket

### PR DESCRIPTION
**Pull request by portertech**
If you do not specify a server, it will assume you want to use the local unix domain socket for syslog.

Linux /dev/log
OS X /var/run/syslog

Specifying a server will make it behave as before.

Let me know what you think :)

### CODE REVIEW

**Comment by melito** [comment]
This is a cool addition and a lot of the code cleanup is good, but I can't merge into master for a couple reasons:

  1) I _think_ the call to Socket.new is unnecessary as event machine supports unix domain sockets:
http://eventmachine.rubyforge.org/EventMachine.html#M000479

  2) Calling EM.syslog_setup without any args (which triggers your additions) blows up on my machine.
      I'm running OSX Lion & REE 1.8.7
      It's actually an odd error because specifying: Socket.new(:UNIX, :DGRAM) results in an ArgumentError
      Throwing the third argument produces another exception Errno::EAFNOSUPPORT

```
  Either way, if EM supports domain sockets, we should probably just be using those - I haven't tested, but I think it may even negate the need for the queue you added.

  Anyway I merged your changes into a branch on my remote here: https://github.com/melito/em-syslog/tree/unix-socket
  I spent a few minutes hacking the beginnings of a test case w/ test-unit
  I moved the old test husk into itest.rb

  I'm a bit tied up today so I can't hack on this at this exact moment, but if you wanna take a stab at it go for it.
```

**Comment by portertech** [comment]
#1 
I tried using connect_unix_domain but /dev/log & /var/run/syslog are datagram sockets.
I'm only aware of send_data for connect_unix_domain, send_datagram is udp socket specific for now :/

#2 
I really should test w/ 1.8.x :)

I need to look into checking for the sockets existence and permissions.
I noticed that /var/run/syslog was not user writable by default.

**Comment by melito** [comment]
Ok, I'll look into the issues at play in further detail once I get done with work stuff this week.

Checkout test.rb - A test case for ensuring that EM can bind to those sockets would be a good first step I think :)

Feel free to change out whatever is in there, I only used test/unit because that's what I've been using a lot with other projects lately.  I'm totally comfortable with mintiest as well, so have at it.

**Comment by portertech** [comment]
ruby 1.8.7 compatibility changes:

https://github.com/portertech/em-syslog/commit/3bd259318dab1ef40b86af813d9a198c23c9a20a

**Pull request closed without merging**
