### PR TITLE
Unix socket update (fixes)

### PR DESCRIPTION
**Pull request by portertech**
Fixed 1.8.x issues.
Added a Git ignore file, it excludes gem builds.
Created tests, using Minitest

### CODE REVIEW

**Comment by eric** [comment]
It might be nice to wrap up the unix domain socket stuff up into a nice EventMachine class.

The stuff going on here might be good to model it after:
https://github.com/eventmachine/eventmachine/blob/master/lib/em/pure_ruby.rb#L902-1012
and
https://github.com/eventmachine/eventmachine/blob/master/lib/em/pure_ruby.rb#L721-765

It looks like it needs a cross between the `EventMachine::EvmaUNIXClient` and `EventMachine::EvmaUDPSocket`...

**Comment by melito** [comment]
Just popping in to let y'all know I haven't forgot about this issue, just been a bit pressed for time the past week.

Thanks for the pointer, Eric.  
That's exactly why I haven't merged everything into master yet. 

I'm thinking the EM::Queue stuff in the commit is only necessary because we're using the Ruby socket object.  
We should be using EM for the networking stuff rather than relying on Socket.
Also this is a syslog client, so moving processing work into the main thread (which I _think_ is what Queue does) seems unnecessary as well.  If we had support for syslog over TCP that wouldn't necessarily be the case as we'd probably need our  own persistent connection delegate for shooting over updates.

Either way, I'll get this cleaned up this week.  If not Monday/Tuesday then on my plane/bus Wednesday.

**Comment by eric** [comment]
Also, it looks like some syslogd's make be using `SOCK_STREAM` instead of (or in addition to?) `SOCK_DGRAM`...

**Comment by melito** [comment]
That's exactly correct.  

That's what I meant by "if we had support for syslog over TCP"

**Comment by eric** [comment]
What I was meaning to say is I believe the local `AF_UNIX` socket can be connected with both `SOCK_STREAM` and `SOCK_DGRAM`.

**Pull request closed without merging**
